# -*- coding: utf-8 -*-
"""NLP-FINAL PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wELzMNdrNjVXU5xfR4VzS5G9xIN37JM6
"""

from datasets import load_dataset
from collections import Counter, defaultdict
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

ds = load_dataset("Jinyan1/COLING_2025_MGT_multingual")

ds["train"][0]

ds["dev"][0]

train_lang_counts = Counter(ds["train"]["lang"])
dev_lang_counts = Counter(ds["dev"]["lang"])

print("Train language distribution:\n", train_lang_counts)
print("\nDev language distribution:\n", dev_lang_counts)

random.seed(42)

target_langs = ["en", "zh", "bg", "id"]
lang_name_map = {
    "en": "English",
    "zh": "Chinese",
    "bg": "Bulgarian",
    "id": "Indonesian"
}

lang_label_counts_full = defaultdict(lambda: Counter())

for lang, label in zip(ds["train"]["lang"], ds["train"]["label"]):
    if lang in target_langs:
        lang_label_counts_full[lang][label] += 1

for lang in target_langs:
    h = lang_label_counts_full[lang][0]
    m = lang_label_counts_full[lang][1]
    print(f"\n{lang_name_map[lang]} ({lang}):")
    print("  Human (0):   ", h)
    print("  Machine (1): ", m)
    print("  Total       : ", h + m)

train_rows = list(ds["train"])

sample_texts = []
sample_labels = []
sample_langs = []

# Languages where we want exactly 4000 samples (≈2000 per class)
fixed_sample_langs = ["en", "zh", "bg"]
samples_per_lang_total = 4000
samples_per_class = samples_per_lang_total // 2  # 2000 human + 2000 machine

print("Target: 4000 samples per language for EN, ZH, BG (≈2000 per class)")
print("Keep all Indonesian as-is.\n")

for lang in fixed_sample_langs:
    human = [row for row in train_rows if row["lang"] == lang and row["label"] == 0]
    machine = [row for row in train_rows if row["lang"] == lang and row["label"] == 1]

    print(f"--- {lang_name_map[lang]} ({lang}) ---")
    print("Available Human:  ", len(human))
    print("Available Machine:", len(machine))

    take_h = min(samples_per_class, len(human))
    take_m = min(samples_per_class, len(machine))

    if take_h < samples_per_class or take_m < samples_per_class:
        print(f"WARNING: {lang} does not have enough for 2000 per class.")
        print(f"Using {take_h} human and {take_m} machine instead.")

    chosen_h = random.sample(human, take_h)
    chosen_m = random.sample(machine, take_m)

    for row in chosen_h + chosen_m:
        sample_texts.append(row["text"])
        sample_labels.append(row["label"])
        sample_langs.append(row["lang"])

# Now add ALL Indonesian samples (id) as-is
id_rows = [row for row in train_rows if row["lang"] == "id"]

print(f"\nAdding all Indonesian samples: {len(id_rows)} rows")

for row in id_rows:
    sample_texts.append(row["text"])
    sample_labels.append(row["label"])
    sample_langs.append(row["lang"])

print("\nTotal samples in final subset:", len(sample_labels))
print("Language distribution:", Counter(sample_langs))

data = {
    "text": sample_texts,
    "label": sample_labels,
    "lang": sample_langs
}
df = pd.DataFrame(data)
df.head()

subset_lang_counts = Counter(df["lang"])

langs_codes = list(subset_lang_counts.keys())
langs_full = [lang_name_map[c] for c in langs_codes]
counts = [subset_lang_counts[c] for c in langs_codes]

plt.figure(figsize=(8,5))
plt.bar(langs_full, counts)
plt.title("Language Distribution in Sampled Subset")
plt.xlabel("Language")
plt.ylabel("Number of Samples")
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.show()

subset_lang_counts

lang_label_counts_subset = defaultdict(lambda: Counter())

for lang, label in zip(df["lang"], df["label"]):
    lang_label_counts_subset[lang][label] += 1

for lang in target_langs:
    print(f"\n{lang_name_map[lang]} ({lang}) in SUBSET:")
    print("  Human (0):   ", lang_label_counts_subset[lang][0])
    print("  Machine (1): ", lang_label_counts_subset[lang][1])

langs_short = target_langs
langs_full = [lang_name_map[l] for l in langs_short]

humans = [lang_label_counts_subset[l][0] for l in langs_short]
machines = [lang_label_counts_subset[l][1] for l in langs_short]

x = np.arange(len(langs_full))

plt.figure(figsize=(10,5))
plt.bar(x - 0.2, humans, width=0.4, label="Human (0)")
plt.bar(x + 0.2, machines, width=0.4, label="Machine (1)")

plt.xticks(x, langs_full)
plt.title("Human vs Machine per Language (Sampled Subset)")
plt.xlabel("Language")
plt.ylabel("Number of Samples")
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.show()

from collections import defaultdict

lengths = defaultdict(list)

for text, lang in zip(df["text"], df["lang"]):
    lengths[lang].append(len(text))

avg_lengths = {lang_name_map[l]: np.mean(lengths[l]) for l in target_langs}
avg_lengths

plt.figure(figsize=(10,5))
plt.bar(avg_lengths.keys(), avg_lengths.values())
plt.title("Average Text Length per Language (Sampled Subset)")
plt.xlabel("Language")
plt.ylabel("Avg text length (characters)")
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.show()

for lang in target_langs:
    ex = df[df["lang"] == lang].iloc[0]["text"]
    print(f"\n=== Example ({lang_name_map[lang]}) ===\n{ex[:500]} ...")

dev_lang_label_counts = defaultdict(lambda: Counter())

for lang, label in zip(ds["dev"]["lang"], ds["dev"]["label"]):
    if lang in target_langs:
        dev_lang_label_counts[lang][label] += 1

print("Per-language label counts in original DEV:")
for lang in target_langs:
    h = dev_lang_label_counts[lang][0]
    m = dev_lang_label_counts[lang][1]
    print(f"\n{lang_name_map[lang]} ({lang}):")
    print("  Human (0):   ", h)
    print("  Machine (1): ", m)
    print("  Total:       ", h + m)

dev_rows = list(ds["dev"])  # full DEV rows

dev_sub_rows = []  # final DEV subset rows (dicts)

# Languages to sample EXACTLY 2000 each (1000 per class)
fixed_langs = ["en", "zh", "bg"]
per_class = 1000   # human and machine each

for lang in fixed_langs:
    human = [r for r in dev_rows if r["lang"] == lang and r["label"] == 0]
    machine = [r for r in dev_rows if r["lang"] == lang and r["label"] == 1]

    print(f"\nSampling DEV for {lang_name_map[lang]} ({lang}):")
    print("  Human available:", len(human))
    print("  Machine available:", len(machine))

    take_h = min(per_class, len(human))
    take_m = min(per_class, len(machine))

    if take_h < per_class or take_m < per_class:
        print(f"  WARNING: Not enough samples. Using {take_h}/{take_m} instead.")

    chosen_h = random.sample(human, take_h)
    chosen_m = random.sample(machine, take_m)

    dev_sub_rows.extend(chosen_h + chosen_m)

# Indonesian kept as-is
id_rows = [r for r in dev_rows if r["lang"] == "id"]

print(f"\nKeeping all Indonesian DEV samples: {len(id_rows)}")
dev_sub_rows.extend(id_rows)

print("\nTotal DEV subset size:", len(dev_sub_rows))
print("Language distribution:", Counter([r['lang'] for r in dev_sub_rows]))

dev_sub_df = pd.DataFrame(dev_sub_rows)
dev_sub_df.head()

subset_lang_counts = Counter(dev_sub_df["lang"])

langs_full = [lang_name_map[l] for l in subset_lang_counts.keys()]
counts = [subset_lang_counts[l] for l in subset_lang_counts.keys()]

plt.figure(figsize=(8,5))
plt.bar(langs_full, counts)
plt.title("Language Distribution — Balanced DEV Subset")
plt.xlabel("Language")
plt.ylabel("Number of Samples")
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.show()

subset_lang_counts

dev_lang_label = defaultdict(lambda: Counter())

for lang, label in zip(dev_sub_df["lang"], dev_sub_df["label"]):
    dev_lang_label[lang][label] += 1

for lang in target_langs:
    print(f"\n{lang_name_map[lang]} ({lang}):")
    print("  Human (0):   ", dev_lang_label[lang][0])
    print("  Machine (1): ", dev_lang_label[lang][1])

langs_short = target_langs
langs_full = [lang_name_map[l] for l in langs_short]

humans   = [dev_lang_label[l][0] for l in langs_short]
machines = [dev_lang_label[l][1] for l in langs_short]

x = np.arange(len(langs_short))

plt.figure(figsize=(10,5))
plt.bar(x - 0.2, humans, width=0.4, label="Human (0)")
plt.bar(x + 0.2, machines, width=0.4, label="Machine (1)")
plt.xticks(x, langs_full)
plt.title("DEV Subset — Human vs Machine per Language")
plt.xlabel("Language")
plt.ylabel("Samples")
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.show()

from sklearn.model_selection import train_test_split
import numpy as np
from collections import Counter

# Extract lists from DEV subset
dev_texts  = dev_sub_df["text"].tolist()
dev_labels = dev_sub_df["label"].tolist()
dev_langs  = dev_sub_df["lang"].tolist()

# Create stratification groups combining language + label
strata = [f"{l}_{y}" for l, y in zip(dev_langs, dev_labels)]

# Split: 50% validation, 50% testing
X_val, X_test, y_val, y_test, lang_val, lang_test = train_test_split(
    dev_texts,
    dev_labels,
    dev_langs,
    test_size=0.5,
    random_state=42,
    stratify=strata       # ← critical (stratify by lang+label)
)

print("VAL size:", len(X_val))
print("TEST size:", len(X_test))

print("\nVAL language distribution:", Counter(lang_val))
print("TEST language distribution:", Counter(lang_test))

print("\nVAL label distribution:", Counter(y_val))
print("TEST label distribution:", Counter(y_test))

# languages = ["en", "zh", "bg", "id"]
# lang_names = ["English", "Chinese", "Bulgarian", "Indonesian"]
val_counts = defaultdict(lambda: Counter())
for lang, label in zip(lang_val, y_val):
    val_counts[lang][label] += 1

val_humans   = [val_counts[l][0] for l in target_langs]
val_machines = [val_counts[l][1] for l in lang_name_map]

x = np.arange(len(target_langs))

plt.figure(figsize=(10,5))
plt.bar(x - 0.2, val_humans,   width=0.4, label="Human (0)")
plt.bar(x + 0.2, val_machines, width=0.4, label="Machine (1)")
plt.xticks(x, lang_name_map)
plt.xlabel("Language")
plt.ylabel("Number of Samples")
plt.title("Validation Set — Human vs Machine Distribution per Language")
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.show()

# Build per-language per-label counts for TEST
test_counts = defaultdict(lambda: Counter())
for lang, label in zip(lang_test, y_test):
    test_counts[lang][label] += 1

# Prepare data
test_humans   = [test_counts[l][0] for l in target_langs]
test_machines = [test_counts[l][1] for l in target_langs]

x = np.arange(len(target_langs))

plt.figure(figsize=(10,5))
plt.bar(x - 0.2, test_humans,   width=0.4, label="Human (0)")
plt.bar(x + 0.2, test_machines, width=0.4, label="Machine (1)")
plt.xticks(x, lang_name_map)
plt.xlabel("Language")
plt.ylabel("Number of Samples")
plt.title("Test Set — Human vs Machine Distribution per Language")
plt.legend()
plt.grid(axis='y', linestyle='--', alpha=0.4)
plt.show()

import re
import numpy as np
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    recall_score,
    classification_report
)

# TRAIN
train_texts  = list(sample_texts)
train_labels = np.array(sample_labels)
train_langs  = np.array(sample_langs)

# VALIDATION (not used in GridSearchCV, but you may use it elsewhere)
val_texts  = list(X_val)
val_labels = np.array(y_val)
val_langs  = np.array(lang_val)

# TEST
test_texts  = list(X_test)
test_labels = np.array(y_test)
test_langs  = np.array(lang_test)

def basic_clean(t: str) -> str:
    t = t.lower()
    t = re.sub(r"\s+", " ", t)
    # keep letters, digits, punctuation, Cyrillic, Chinese
    t = re.sub(r"[^0-9a-záéíóúüñçàèìòùäëïöüß.,?!\u0400-\u04FF\u4e00-\u9fff ]", "", t)
    return t.strip()

train_clean = [basic_clean(t) for t in train_texts]
val_clean   = [basic_clean(t) for t in val_texts]
test_clean  = [basic_clean(t) for t in test_texts]

len(train_clean), len(val_clean), len(test_clean)

def run_mnb(
    train_texts, train_labels,
    test_texts,  test_labels,
    mode_name="TF-IDF baseline"
):
    """
    TF-IDF + MultinomialNB with GridSearchCV over alpha.
    """
    print(f"\n==============================")
    print(f"MultinomialNB GridSearchCV ({mode_name})")
    print(f"==============================")

    pipe = Pipeline([
        ("tfidf", TfidfVectorizer(
            max_features=50000,
            ngram_range=(1, 2)
        )),
        ("clf", MultinomialNB())
    ])

    param_grid = {
        "clf__alpha": [0.1, 0.5, 1.0]
    }

    grid = GridSearchCV(
        estimator=pipe,
        param_grid=param_grid,
        cv=3,
        scoring="accuracy",
        n_jobs=-1,
        verbose=1
    )

    grid.fit(train_texts, train_labels)

    print("\n[MNB] Best params:", grid.best_params_)
    print("[MNB] Best CV accuracy:", grid.best_score_)

    best_model = grid.best_estimator_
    test_pred = best_model.predict(test_texts)

    # Performance metrics
    acc = accuracy_score(test_labels, test_pred)
    f1  = f1_score(test_labels, test_pred)
    rec = recall_score(test_labels, test_pred)

    print(f"\n[MNB] TEST Accuracy: {acc:.4f}")
    print(f"[MNB] TEST F1-score: {f1:.4f}")
    print(f"[MNB] TEST Recall:   {rec:.4f}")

    print("\n[MNB] Classification Report:")
    print(classification_report(test_labels, test_pred, digits=4))

    return {
        "best_params": grid.best_params_,
        "cv_best_acc": grid.best_score_,
        "test_acc":    acc,
        "test_f1":     f1,
        "test_rec":    rec,
        "test_pred":   test_pred,
        "model":       best_model
    }

def run_logistic(
    train_texts, train_labels,
    test_texts,  test_labels,
    mode_name="TF-IDF baseline"
):
    """
    TF-IDF + Logistic Regression with GridSearchCV over C and class_weight.
    """
    print(f"\n==============================")
    print(f"Logistic Regression GridSearchCV ({mode_name})")
    print(f"==============================")

    pipe = Pipeline([
        ("tfidf", TfidfVectorizer(
            max_features=50000,
            ngram_range=(1, 2)
        )),
        ("clf", LogisticRegression(
            max_iter=300,
            n_jobs=-1
        ))
    ])

    param_grid = {
        "clf__C": [0.5, 1.0, 3.0],
        "clf__class_weight": [None, "balanced"]
    }

    grid = GridSearchCV(
        estimator=pipe,
        param_grid=param_grid,
        cv=3,
        scoring="accuracy",
        n_jobs=-1,
        verbose=1
    )

    grid.fit(train_texts, train_labels)

    print("\n[LR] Best params:", grid.best_params_)
    print("[LR] Best CV accuracy:", grid.best_score_)

    best_model = grid.best_estimator_
    test_pred = best_model.predict(test_texts)

    # Performance metrics
    acc = accuracy_score(test_labels, test_pred)
    f1  = f1_score(test_labels, test_pred)
    rec = recall_score(test_labels, test_pred)

    print(f"\n[LR] TEST Accuracy: {acc:.4f}")
    print(f"[LR] TEST F1-score: {f1:.4f}")
    print(f"[LR] TEST Recall:   {rec:.4f}")

    print("\n[LR] Classification Report:")
    print(classification_report(test_labels, test_pred, digits=4))

    return {
        "best_params": grid.best_params_,
        "cv_best_acc": grid.best_score_,
        "test_acc":    acc,
        "test_f1":     f1,
        "test_rec":    rec,
        "test_pred":   test_pred,
        "model":       best_model
    }

def plot_confusion_matrix(cm, title="Confusion Matrix"):
    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt="d",
                cmap="Blues",
                xticklabels=["Human (0)", "Machine (1)"],
                yticklabels=["Human (0)", "Machine (1)"])
    plt.title(title)
    plt.ylabel("True Label")
    plt.xlabel("Predicted Label")
    plt.tight_layout()
    plt.show()

def plot_overall_confusion_matrix(y_true, y_pred, experiment_name="", model_name=""):
    cm = confusion_matrix(y_true, y_pred, labels=[0,1])
    title = f"{experiment_name} — {model_name}\nOverall Confusion Matrix"
    plot_confusion_matrix(cm, title=title)

def plot_confusion_per_language(y_true, y_pred, langs,
                                experiment_name="", model_name=""):

    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    langs  = np.array(langs)

    for lang in sorted(set(langs)):
        mask = (langs == lang)
        yt = y_true[mask]
        yp = y_pred[mask]

        name = LANG_MAP.get(lang, lang)
        cm = confusion_matrix(yt, yp, labels=[0,1])

        title = (f"{experiment_name} — {model_name}\n"
                 f"Language: {name} ({lang})")
        plot_confusion_matrix(cm, title)

LANG_MAP = {
    "en": "English",
    "zh": "Chinese",
    "bg": "Bulgarian",
    "id": "Indonesian"
}

def evaluate_per_language(y_true, y_pred, langs,
                          experiment_name,
                          model_name):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    langs  = np.array(langs)

    header = f"{experiment_name} — {model_name}"
    print("\n" + "="*len(header))
    print(header)
    print("="*len(header))

    # Overall metrics
    overall_acc = accuracy_score(y_true, y_pred)
    print(f"\n[OVERALL] Accuracy: {overall_acc:.4f}")
    print("\n[OVERALL] Classification report:")
    print(classification_report(y_true, y_pred, digits=4))

    cm = confusion_matrix(y_true, y_pred, labels=[0,1])
    print("\n[OVERALL] Confusion matrix (rows=true, cols=pred):")
    print("labels: [0=Human, 1=Machine]")
    print(cm)

    # Per-language
    print("\n=== Per-language metrics ===")
    for lang in sorted(set(langs)):
        mask = (langs == lang)
        n = mask.sum()
        if n == 0:
            continue

        yt = y_true[mask]
        yp = y_pred[mask]

        acc = accuracy_score(yt, yp)
        prec, rec, f1, _ = precision_recall_fscore_support(
            yt, yp, average="binary", pos_label=1, zero_division=0
        )

        name = LANG_MAP.get(lang, lang)
        print(f"\n[{name} ({lang})] n={n}")
        print(f"  Accuracy : {acc:.4f}")
        print(f"  Precision: {prec:.4f}")
        print(f"  Recall   : {rec:.4f}")
        print(f"  F1-score : {f1:.4f}")

        cm_lang = confusion_matrix(yt, yp, labels=[0,1])
        print("  Confusion matrix (rows=true, cols=pred):")
        print("    labels: [0=Human, 1=Machine]")
        print("   ", cm_lang)

mnb_results = run_mnb(
    train_texts=train_clean,
    train_labels=train_labels,
    test_texts=test_clean,
    test_labels=test_labels,
    mode_name="TF-IDF baseline"
)

plot_overall_confusion_matrix(
    y_true=test_labels,
    y_pred=mnb_results["test_pred"],
    experiment_name="TF-IDF baseline",
    model_name="MNB"
)

plot_confusion_per_language(
    y_true=test_labels,
    y_pred=mnb_results["test_pred"],
    langs=test_langs,
    experiment_name="TF-IDF baseline",
    model_name="MNB"
)

lr_results = run_logistic(
    train_texts=train_clean,
    train_labels=train_labels,
    test_texts=test_clean,
    test_labels=test_labels,
    mode_name="TF-IDF baseline"
)

plot_overall_confusion_matrix(
    y_true=test_labels,
    y_pred=lr_results["test_pred"],
    experiment_name="TF-IDF baseline",
    model_name="Logistic Regression"
)

plot_confusion_per_language(
    y_true=test_labels,
    y_pred=lr_results["test_pred"],
    langs=test_langs,
    experiment_name="TF-IDF baseline",
    model_name="Logistic Regression"
)

"""**Word2Vec**"""

!pip install jieba

# =======================
# CELL 1: Setup & Tokenization
# =======================
import re
import numpy as np
import pandas as pd
import jieba
from collections import Counter

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    precision_recall_fscore_support,
    confusion_matrix,
)

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, TensorDataset

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# -----------------------
# Train / Val / Test splits (you already prepared these)
# -----------------------
train_texts = list(sample_texts)
train_labels = np.array(sample_labels)
train_langs  = np.array(sample_langs)

val_texts  = list(X_val)
val_labels = np.array(y_val)
val_langs  = np.array(lang_val)

test_texts  = list(X_test)
test_labels = np.array(y_test)
test_langs  = np.array(lang_test)

print("Train size:", len(train_texts))
print("Val size:", len(val_texts))
print("Test size:", len(test_texts))
print("Train lang distribution:", Counter(train_langs))

# -----------------------
# Cleaning + tokenization
# -----------------------
def basic_clean(t: str) -> str:
    t = t.lower()
    t = re.sub(r"\s+", " ", t)
    # keep latin, digits, punctuation, Cyrillic, Chinese
    t = re.sub(r"[^0-9a-záéíóúüñçàèìòùäëïöüß.,?!\u0400-\u04FF\u4e00-\u9fff ]", "", t)
    return t.strip()

def tokenize(text: str, lang: str):
    text = basic_clean(text)
    if lang == "zh":
        return list(jieba.cut(text))
    else:
        return text.split()

train_tokens = [tokenize(t, l) for t, l in zip(train_texts, train_langs)]
val_tokens   = [tokenize(t, l) for t, l in zip(val_texts,   val_langs)]
test_tokens  = [tokenize(t, l) for t, l in zip(test_texts,  test_langs)]

print("Example tokens (train[0]):", train_tokens[0][:20])

LANG_MAP = {
    "en": "English",
    "zh": "Chinese",
    "bg": "Bulgarian",
    "id": "Indonesian",
}

# --------- Build vocabulary from TRAIN ONLY ---------
vocab_list = sorted({tok for sent in train_tokens for tok in sent})

def create_word_to_index(vocab_list):
    word_to_index = {"<OOV>": 0}
    for idx, word in enumerate(vocab_list, start=1):
        word_to_index[word] = idx
    return word_to_index

word_to_index = create_word_to_index(vocab_list)
vocab_size = len(word_to_index)
print("Vocab size (with <OOV>):", vocab_size)

# --------- Generate CBOW dataset: surroundings indices ---------
def generate_cbow_dataset(token_lists, window_size, word_to_index):
    surroundings = []
    targets = []

    for tokens in token_lists:
        if len(tokens) < 2 * window_size + 1:
            continue

        for i in range(window_size, len(tokens) - window_size):
            center_word = tokens[i]
            center_idx = word_to_index.get(center_word, word_to_index["<OOV>"])

            ctx_indices = []
            for j in range(i - window_size, i + window_size + 1):
                if j == i:
                    continue
                w = tokens[j]
                ctx_indices.append(word_to_index.get(w, word_to_index["<OOV>"]))

            surroundings.append(ctx_indices)
            targets.append(center_idx)

    surroundings = torch.tensor(surroundings, dtype=torch.long)
    targets = torch.tensor(targets, dtype=torch.long)
    return surroundings, targets

class CBOW(nn.Module):
    def __init__(self, vocab_size, embed_dim):
        super().__init__()
        # Learned lookup table instead of linear(one-hot)
        self.embedding = nn.Embedding(vocab_size, embed_dim)
        # After averaging embeddings → predict center word
        self.linear_out = nn.Linear(embed_dim, vocab_size, bias=False)

    def forward(self, idx_context):
        """
        idx_context: [batch, 2W]  integer word indices
        """
        emb = self.embedding(idx_context)    # [batch, 2W, D]
        avg = emb.mean(dim=1)                # [batch, D]
        out = self.linear_out(avg)           # [batch, vocab]
        return out

# --------- CBOW training epoch ---------
def train_cbow_epoch(model, loader, optimizer, loss_fn, vocab_size):
    model.train()
    total_loss = 0.0

    for surr, tar in loader:
        surr, tar = surr.to(device), tar.to(device)

        optimizer.zero_grad()
        logits = model(surr)        # NO one-hot → direct index lookup
        loss = loss_fn(logits, tar)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * surr.size(0)

    return total_loss / len(loader.dataset)

# --------- CBOW validation (for val_loss printing) ---------
def eval_cbow(model, loader, loss_fn, vocab_size):
    model.eval()
    total_loss = 0.0

    with torch.no_grad():
        for surr, tar in loader:
            surr, tar = surr.to(device), tar.to(device)
            logits = model(surr)
            loss = loss_fn(logits, tar)
            total_loss += loss.item() * surr.size(0)

    return total_loss / len(loader.dataset)

# --------- Extract word embeddings from CBOW ---------
def create_word_to_embedding(vocab_list, model, word_to_index):
    # embedding.weight: [V, D]
    W = model.embedding.weight.detach().cpu()

    word_to_embedding = {}
    for w in vocab_list:
        idx = word_to_index.get(w, word_to_index["<OOV>"])
        word_to_embedding[w] = W[idx]

    word_to_embedding["<OOV>"] = W[word_to_index["<OOV>"]]
    return word_to_embedding

# --------- Build sentence/document embeddings ---------
def get_doc_embedding(tokens, word_to_embedding, emb_dim):
    vecs = []

    for w in tokens:
        if w in word_to_embedding:
            vecs.append(word_to_embedding[w])
        else:
            vecs.append(word_to_embedding["<OOV>"])

    if not vecs:
        return torch.zeros(emb_dim)

    mat = torch.stack(vecs, dim=0)
    return mat.mean(dim=0)   # average word vectors

def build_doc_embeddings(token_lists, word_to_embedding, emb_dim):
    embs = []
    for toks in token_lists:
        embs.append(get_doc_embedding(toks, word_to_embedding, emb_dim).numpy())
    return np.vstack(embs).astype(np.float32)

# --------- Classifier MLP ---------
class SentimentClassifier(nn.Module):
    def __init__(self, embedding_dim, hidden_dim=128, num_classes=2):
        super().__init__()
        self.fc1 = nn.Linear(embedding_dim, hidden_dim)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.3)
        self.fc2 = nn.Linear(hidden_dim, num_classes)

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc2(x)
        return x

# --------- Classifier train/eval ---------
def train_cls_epoch(model, loader, optimizer, loss_fn):
    model.train()
    total_loss = 0.0
    for Xb, yb in loader:
        Xb, yb = Xb.to(device), yb.to(device)
        optimizer.zero_grad()
        logits = model(Xb)
        loss = loss_fn(logits, yb)
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * Xb.size(0)
    return total_loss / len(loader.dataset)

def eval_cls(model, loader, loss_fn):
    model.eval()
    total_loss = 0.0
    all_y, all_p = [], []

    with torch.no_grad():
        for Xb, yb in loader:
            Xb, yb = Xb.to(device), yb.to(device)
            logits = model(Xb)
            loss = loss_fn(logits, yb)
            total_loss += loss.item() * Xb.size(0)

            preds = torch.argmax(logits, dim=1)
            all_y.append(yb.cpu().numpy())
            all_p.append(preds.cpu().numpy())

    all_y = np.concatenate(all_y)
    all_p = np.concatenate(all_p)
    acc = accuracy_score(all_y, all_p)
    return total_loss / len(loader.dataset), acc, all_y, all_p

# =======================
# CELL 3: Train Manual CBOW (With Train + Val Loss, Optimized for GPU Safety)
# =======================

cbow_models = {}   # (W, D) -> trained CBOW model
cbow_embeds = {}   # (W, D) -> word_to_embedding dict

# SAFE SETTINGS
window_list = [5]        # Only one window size
emb_dim_list = [300]     # Only one embedding dimension
cbow_epochs = 8          # Only one epoch (you can set to 2 if GPU is green)

# LIMIT CBOW PAIRS (CRITICAL FOR STABILITY)
max_train_cbow = 20000   # from millions → 20k
max_val_cbow   = 5000    # from ~1M → 5k

for W in window_list:
    print(f"\n### Training CBOW for WINDOW = {W} ###")

    # ---- Generate CBOW training pairs ----
    train_surr, train_tars = generate_cbow_dataset(train_tokens, W, word_to_index)
    print("Original CBOW train examples:", train_surr.shape[0])

    # ---- Downsample CBOW training ----
    if train_surr.size(0) > max_train_cbow:
        train_surr = train_surr[:max_train_cbow]
        train_tars = train_tars[:max_train_cbow]
    print("Using CBOW TRAIN examples:", train_surr.shape[0])

    # ---- Generate CBOW validation pairs ----
    val_surr, val_tars = generate_cbow_dataset(val_tokens, W, word_to_index)
    print("Original CBOW val examples:", val_surr.shape[0])

    # ---- Downsample CBOW validation ----
    if val_surr.size(0) > max_val_cbow:
        val_surr = val_surr[:max_val_cbow]
        val_tars = val_tars[:max_val_cbow]
    print("Using CBOW VAL examples:", val_surr.shape[0])

    # ---- Build datasets ----
    train_ds = TensorDataset(train_surr, train_tars)
    val_ds   = TensorDataset(val_surr, val_tars)

    # ---- SAFE BATCH SIZE ----
    train_loader = DataLoader(train_ds, batch_size=256, shuffle=True)
    val_loader   = DataLoader(val_ds,   batch_size=256, shuffle=False)

    for D in emb_dim_list:
        print(f"\n=== CBOW MODEL | window={W}, emb_dim={D} ===")

        cbow_model = CBOW(vocab_size=vocab_size, embed_dim=D).to(device)
        optimizer = torch.optim.Adam(cbow_model.parameters(), lr=5e-4)
        loss_fn = nn.CrossEntropyLoss()

        for ep in range(1, cbow_epochs + 1):
            train_loss = train_cbow_epoch(
                cbow_model, train_loader, optimizer, loss_fn, vocab_size
            )
            val_loss = eval_cbow(
                cbow_model, val_loader, loss_fn, vocab_size
            )
            print(
                f"[CBOW] Epoch {ep}/{cbow_epochs} | "
                f"train_loss={train_loss:.4f} | val_loss={val_loss:.4f}"
            )

        # Save CBOW model & embeddings
        cbow_models[(W, D)] = cbow_model
        word_to_emb = create_word_to_embedding(vocab_list, cbow_model, word_to_index)
        cbow_embeds[(W, D)] = word_to_emb

print("\n✔ CBOW training finished for all (window, emb_dim) combinations.")

# =======================
# CELL 4: Train Classifier using CBOW Embeddings & Evaluate
# =======================

results = []
best_cfg = None
best_val_acc = -1.0

loss_fn_cls = nn.CrossEntropyLoss()

for (W, D), word_to_emb in cbow_embeds.items():
    print(f"\n=== Classifier Experiment | window={W}, emb_dim={D} ===")

    # Build sentence embeddings for train/val/test
    X_train = build_doc_embeddings(train_tokens, word_to_emb, D)
    X_val   = build_doc_embeddings(val_tokens,   word_to_emb, D)
    X_test  = build_doc_embeddings(test_tokens,  word_to_emb, D)

    train_ds = TensorDataset(
        torch.tensor(X_train, dtype=torch.float32),
        torch.tensor(train_labels, dtype=torch.long)
    )
    val_ds = TensorDataset(
        torch.tensor(X_val, dtype=torch.float32),
        torch.tensor(val_labels, dtype=torch.long)
    )
    test_ds = TensorDataset(
        torch.tensor(X_test, dtype=torch.float32),
        torch.tensor(test_labels, dtype=torch.long)
    )

    train_loader = DataLoader(train_ds, batch_size=64, shuffle=True)
    val_loader   = DataLoader(val_ds,   batch_size=64, shuffle=False)
    test_loader  = DataLoader(test_ds,  batch_size=64, shuffle=False)

    cls_model = SentimentClassifier(embedding_dim=D).to(device)
    optimizer = torch.optim.Adam(cls_model.parameters(), lr=1e-3)

    best_val_for_combo = -1.0
    best_state_for_combo = None
    cls_epochs = 11

    for ep in range(1, cls_epochs + 1):
        train_loss = train_cls_epoch(cls_model, train_loader, optimizer, loss_fn_cls)
        val_loss, val_acc, _, _ = eval_cls(cls_model, val_loader, loss_fn_cls)

        print(
            f"[CLS] Epoch {ep}/{cls_epochs} | "
            f"train_loss={train_loss:.4f} | "
            f"val_loss={val_loss:.4f} | "
            f"val_acc={val_acc:.4f}"
        )

        if val_acc > best_val_for_combo:
            best_val_for_combo = val_acc
            best_state_for_combo = cls_model.state_dict()

    # Load best classifier for this (W, D)
    cls_model.load_state_dict(best_state_for_combo)
    test_loss, test_acc, y_true, y_pred = eval_cls(cls_model, test_loader, loss_fn_cls)

    results.append({
        "window": W,
        "emb_dim": D,
        "val_acc": float(best_val_for_combo),
        "test_acc": float(test_acc)
    })

    # Track global best configuration
    if best_val_for_combo > best_val_acc:
        best_val_acc = best_val_for_combo
        best_cfg = {
            "window": W,
            "emb_dim": D,
            "val_acc": best_val_for_combo,
            "test_acc": test_acc,
            "y_true": y_true,
            "y_pred": y_pred
        }

print("\n=== All CBOW + MLP results ===")
results_df = pd.DataFrame(results)
display(results_df)

print("\n=== Best CBOW + MLP configuration ===")
print("window:", best_cfg["window"],
      "| emb_dim:", best_cfg["emb_dim"],
      "| val_acc:", best_cfg["val_acc"],
      "| test_acc:", best_cfg["test_acc"])

y_true_best = best_cfg["y_true"]
y_pred_best = best_cfg["y_pred"]

evaluate_per_language(
    y_true=y_true_best,
    y_pred=y_pred_best,
    langs=test_langs,
    experiment_name=f"Best Manual CBOW (win={best_cfg['window']}, dim={best_cfg['emb_dim']})",
    model_name="Assignment-style CBOW + MLP"
)

plot_overall_confusion_matrix(
    y_true=y_true_best,
    y_pred=y_pred_best,
    experiment_name=f"Best Manual CBOW (win={best_cfg['window']}, dim={best_cfg['emb_dim']})",
    model_name="Assignment-style CBOW + MLP"
)

plot_confusion_per_language(
    y_true=y_true,
    y_pred=y_pred_best,
    langs=test_langs,
    experiment_name=f"Best Manual CBOW (win={best_cfg['window']}, dim={best_cfg['emb_dim']})",
    model_name="Assignment-style CBOW + MLP"
)

"""**Pretrained Word2Vec**"""

# ================================================
# 1. Create folder
# ================================================
import os

FASTTEXT_PATH = "/content/fasttext/"
os.makedirs(FASTTEXT_PATH, exist_ok=True)

print("Folder created at:", FASTTEXT_PATH)

# ================================================
# 2. Download fastText multilingual vectors
# ================================================
import urllib.request

files = {
    "cc.en.300.vec.gz": "https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.vec.gz",
    "cc.zh.300.vec.gz": "https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.zh.300.vec.gz",
    "cc.bg.300.vec.gz": "https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.bg.300.vec.gz",
    "cc.id.300.vec.gz": "https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.id.300.vec.gz"
}

print("\nDownloading files... (takes time, ~4–5 GB)")
for filename, url in files.items():
    out_path = FASTTEXT_PATH + filename
    if not os.path.exists(out_path):
        print(f"Downloading {filename} ...")
        urllib.request.urlretrieve(url, out_path)
    else:
        print(f"{filename} already exists — skipping.")

print("\nAll downloads completed.")

import gzip
import shutil

print("\nExtracting files... (takes time)")

for filename in files.keys():
    gz_path = FASTTEXT_PATH + filename
    vec_path = gz_path.replace(".gz", "")

    if not os.path.exists(vec_path):
        print(f"Extracting {filename} ...")
        with gzip.open(gz_path, 'rb') as f_in:
            with open(vec_path, 'wb') as f_out:
                shutil.copyfileobj(f_in, f_out)
    else:
        print(f"{vec_path} already extracted — skipping.")

print("\nExtraction complete.")

pip install gensim

# ================================================
# 4. Load all 4 models with gensim
# ================================================
from gensim.models import KeyedVectors

print("\nLoading models (this is slow)...")

ft_models = {
    "en": KeyedVectors.load_word2vec_format(FASTTEXT_PATH + "cc.en.300.vec", binary=False),
    "zh": KeyedVectors.load_word2vec_format(FASTTEXT_PATH + "cc.zh.300.vec", binary=False),
    "bg": KeyedVectors.load_word2vec_format(FASTTEXT_PATH + "cc.bg.300.vec", binary=False),
    "id": KeyedVectors.load_word2vec_format(FASTTEXT_PATH + "cc.id.300.vec", binary=False),
}

print("\nAll fastText models loaded successfully!")

FASTTEXT_PATH = "/content/fasttext/"  # change to your path

ft_models = {
    "en": KeyedVectors.load_word2vec_format(FASTTEXT_PATH + "cc.en.300.vec", binary=False),
    "zh": KeyedVectors.load_word2vec_format(FASTTEXT_PATH + "cc.zh.300.vec", binary=False),
    "bg": KeyedVectors.load_word2vec_format(FASTTEXT_PATH + "cc.bg.300.vec", binary=False),
    "id": KeyedVectors.load_word2vec_format(FASTTEXT_PATH + "cc.id.300.vec", binary=False),
}
FT_DIM = 300
print("Loaded fastText models for en/zh/bg/id.")

def sentence_embedding_fasttext(tokens, lang, ft_models, dim):
    model = ft_models[lang]
    vecs = []
    for w in tokens:
        if w in model.key_to_index:
            vecs.append(model[w])
    if not vecs:
        return np.zeros(dim, dtype=np.float32)
    return np.mean(vecs, axis=0).astype(np.float32)

def build_fasttext_embeddings(tokens_list, langs_list, ft_models, dim):
    return np.vstack([
        sentence_embedding_fasttext(toks, lang, ft_models, dim)
        for toks, lang in zip(tokens_list, langs_list)
    ]).astype(np.float32)

X_train_ft = build_fasttext_embeddings(train_tokens, train_langs, ft_models, FT_DIM)
X_val_ft   = build_fasttext_embeddings(val_tokens,   val_langs,   ft_models, FT_DIM)
X_test_ft  = build_fasttext_embeddings(test_tokens,  test_langs,  ft_models, FT_DIM)

print("fastText embeddings shapes:")
print("Train:", X_train_ft.shape)
print("Val  :", X_val_ft.shape)
print("Test :", X_test_ft.shape)

train_ds_ft = TensorDataset(
    torch.tensor(X_train_ft, dtype=torch.float32),
    torch.tensor(train_labels, dtype=torch.long)
)
val_ds_ft = TensorDataset(
    torch.tensor(X_val_ft, dtype=torch.float32),
    torch.tensor(val_labels, dtype=torch.long)
)
test_ds_ft = TensorDataset(
    torch.tensor(X_test_ft, dtype=torch.float32),
    torch.tensor(test_labels, dtype=torch.long)
)

train_loader_ft = DataLoader(train_ds_ft, batch_size=64, shuffle=True)
val_loader_ft   = DataLoader(val_ds_ft,   batch_size=64, shuffle=False)
test_loader_ft  = DataLoader(test_ds_ft,  batch_size=64, shuffle=False)

EPOCHS_FT = 5
model_ft = SentimentClassifier(embedding_dim=FT_DIM).to(device)
optimizer_ft = torch.optim.Adam(model_ft.parameters(), lr=1e-3)
loss_fn_cls = nn.CrossEntropyLoss()

best_val_acc_ft = 0.0
best_state_ft = None

for ep in range(1, EPOCHS_FT + 1):
    train_loss = train_cls_epoch(model_ft, train_loader_ft, optimizer_ft, loss_fn_cls)
    val_loss, val_acc, _, _ = eval_cls(model_ft, val_loader_ft, loss_fn_cls)
    print(f"[fastText] Epoch {ep}/{EPOCHS_FT} | "
          f"train_loss={train_loss:.4f} | val_acc={val_acc:.4f}")
    if val_acc > best_val_acc_ft:
        best_val_acc_ft = val_acc
        best_state_ft = model_ft.state_dict()

if best_state_ft is not None:
    model_ft.load_state_dict(best_state_ft)

test_loss_ft, test_acc_ft, y_true_ft, y_pred_ft = eval_cls(model_ft, test_loader_ft, loss_fn_cls)
print(f"\n[fastText] TEST ACCURACY = {test_acc_ft:.4f}")

evaluate_per_language(
    y_true=y_true_ft,
    y_pred=y_pred_ft,
    langs=test_langs,
    experiment_name="Pretrained fastText (4 languages)",
    model_name="MLP"
)

plot_overall_confusion_matrix(
    y_true=y_true_ft,
    y_pred=y_pred_ft,
    experiment_name="Pretrained fastText (4 languages)",
    model_name="MLP"
)

plot_confusion_per_language(
    y_true=y_true_ft,
    y_pred=y_pred_ft,
    langs=test_langs,
    experiment_name="Pretrained fastText (4 languages)",
    model_name="MLP"
)

print("Example tokens:", train_tokens[0][:20])

from gensim.models import Word2Vec

def sentence_embedding(tokens, model, dim):
    vecs = [model.wv[t] for t in tokens if t in model.wv]
    if not vecs:
        return np.zeros(dim, dtype=np.float32)
    return np.mean(vecs, axis=0).astype(np.float32)

def build_embeddings(token_list, model, dim):
    return np.vstack([sentence_embedding(toks, model, dim) for toks in token_list])

class W2VDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

class MLPClassifier(nn.Module):
    def __init__(self, in_dim, hid=256, drop=0.3):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, hid),
            nn.ReLU(),
            nn.Dropout(drop),
            nn.Linear(hid, hid//2),
            nn.ReLU(),
            nn.Dropout(drop),
            nn.Linear(hid//2, 2)
        )
    def forward(self, x):
        return self.net(x)

def eval_loader(model, loader):
    model.eval()
    all_y, all_p = [], []
    with torch.no_grad():
        for xb, yb in loader:
            xb, yb = xb.to(device), yb.to(device)
            preds = model(xb).argmax(dim=1)
            all_y.append(yb.cpu().numpy())
            all_p.append(preds.cpu().numpy())
    all_y = np.concatenate(all_y)
    all_p = np.concatenate(all_p)
    return accuracy_score(all_y, all_p), all_y, all_p

def run_gensim_w2v_grid(
    window_list=[3, 4, 5],
    dim_list=[100, 200, 300],
    w2v_epochs=10,
    cls_epochs=10
):

    results = []
    best_cfg = None
    best_val = -1

    for W in window_list:
        for D in dim_list:

            print(f"\n=== EXP: Gensim Word2Vec (CBOW) + MLP | window={W}, dim={D} ===")

            # Train Word2Vec CBOW
            w2v = Word2Vec(
                sentences=train_tokens,
                vector_size=D,
                window=W,
                min_count=2,
                workers=4,
                sg=0,            # CBOW
                epochs=w2v_epochs,
            )

            print("  Word2Vec vocab size:", len(w2v.wv))

            # Build embeddings
            X_train = build_embeddings(train_tokens, w2v, D)
            X_val   = build_embeddings(val_tokens,   w2v, D)
            X_test  = build_embeddings(test_tokens,  w2v, D)

            train_ds = W2VDataset(X_train, train_labels)
            val_ds   = W2VDataset(X_val,   val_labels)
            test_ds  = W2VDataset(X_test,  test_labels)

            train_loader = DataLoader(train_ds, batch_size=64, shuffle=True)
            val_loader   = DataLoader(val_ds,   batch_size=64, shuffle=False)
            test_loader  = DataLoader(test_ds,  batch_size=64, shuffle=False)

            # Train classifier
            model = MLPClassifier(D).to(device)
            opt = torch.optim.Adam(model.parameters(), lr=1e-3)
            loss_fn = nn.CrossEntropyLoss()

            best_val_local = 0
            best_state = None

            for ep in range(1, cls_epochs+1):
                model.train()
                total_loss = 0

                for xb, yb in train_loader:
                    xb, yb = xb.to(device), yb.to(device)
                    opt.zero_grad()
                    loss = loss_fn(model(xb), yb)
                    loss.backward()
                    opt.step()
                    total_loss += loss.item()

                val_acc, _, _ = eval_loader(model, val_loader)
                print(f"  Epoch {ep:02d} | loss={total_loss:.3f} | val_acc={val_acc:.4f}")

                if val_acc > best_val_local:
                    best_val_local = val_acc
                    best_state = model.state_dict()

            # Restore best classifier
            model.load_state_dict(best_state)
            test_acc, y_true, y_pred = eval_loader(model, test_loader)

            results.append({
                "window": W,
                "dim": D,
                "val_acc": best_val_local,
                "test_acc": test_acc
            })

            if best_val_local > best_val:
                best_val = best_val_local
                best_cfg = {
                    "window": W,
                    "emb_dim": D,
                    "val_acc": best_val_local,
                    "test_acc": test_acc,
                    "y_true": y_true,
                    "y_pred": y_pred,
                }

            print(f"  >> Finished: best_val={best_val_local:.4f} | test_acc={test_acc:.4f}")

    return pd.DataFrame(results), best_cfg

w2v_results_df, best_w2v = run_gensim_w2v_grid(
    window_list=[3, 4, 5],
    dim_list=[100, 200, 300],
    w2v_epochs=10,
    cls_epochs=10
)

w2v_results_df

y_true_best_w2v = best_w2v["y_true"]
y_pred_best_w2v = best_w2v["y_pred"]

exp_dim = best_w2v.get("dim", best_w2v.get("emb_dim"))

evaluate_per_language(
    y_true=y_true_best_w2v,
    y_pred=y_pred_best_w2v,
    langs=test_langs,
    experiment_name=f"Best Word2Vec CBOW (win={best_w2v['window']}, dim={exp_dim})",
    model_name="MLP"
)

plot_overall_confusion_matrix(
    y_true=y_true_best_w2v,
    y_pred=y_pred_best_w2v,
    experiment_name=f"Best Word2Vec CBOW (win={best_w2v['window']}, dim={exp_dim})",
    model_name="MLP"
)

plot_confusion_per_language(
    y_true=y_true_best_w2v,
    y_pred=y_pred_best_w2v,
    langs=test_langs,
    experiment_name=f"Best Word2Vec CBOW (win={best_w2v['window']}, dim={exp_dim})",
    model_name="MLP"
)

"""# MBERT"""

!pip install -q sentence-transformers

import torch
import numpy as np
from sentence_transformers import SentenceTransformer

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

sbert_model_name = "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
sbert = SentenceTransformer(sbert_model_name, device=str(device))

X_train_sbert = sbert.encode(
    train_texts, batch_size=64, convert_to_numpy=True,
    show_progress_bar=True
)
X_val_sbert = sbert.encode(
    val_texts, batch_size=64, convert_to_numpy=True,
    show_progress_bar=True
)
X_test_sbert = sbert.encode(
    test_texts, batch_size=64, convert_to_numpy=True,
    show_progress_bar=True
)

X_train_sbert.shape, X_val_sbert.shape, X_test_sbert.shape

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, f1_score, recall_score

clf_sbert = LogisticRegression(max_iter=2000, n_jobs=-1)
clf_sbert.fit(X_train_sbert, train_labels)

# validation
val_pred_sbert = clf_sbert.predict(X_val_sbert)
print("SBERT + LogReg – VAL acc:", accuracy_score(val_labels, val_pred_sbert))

# test
y_true_sbert = np.array(test_labels)
y_pred_sbert = clf_sbert.predict(X_test_sbert)

print("SBERT + LogReg – TEST acc:", accuracy_score(y_true_sbert, y_pred_sbert))

print("=== SBERT + LogReg – Overall TEST metrics ===")
acc_sbert  = accuracy_score(y_true_sbert, y_pred_sbert)
f1_sbert   = f1_score(y_true_sbert, y_pred_sbert, pos_label=1)
rec_sbert  = recall_score(y_true_sbert, y_pred_sbert, pos_label=1)

print(f"Accuracy: {acc_sbert:.4f}")
print(f"F1-score (label=1): {f1_sbert:.4f}")
print(f"Recall   (label=1): {rec_sbert:.4f}\n")

print(classification_report(y_true_sbert, y_pred_sbert, digits=4))

# overall confusion matrix
plot_overall_confusion_matrix(
    y_true=y_true_sbert,
    y_pred=y_pred_sbert,
    experiment_name="SBERT (multilingual MiniLM)",
    model_name="LogReg"
)

plot_confusion_per_language(
    y_true=y_true_sbert,
    y_pred=y_pred_sbert,
    langs=test_langs,
    experiment_name="SBERT (multilingual MiniLM)",
    model_name="LogReg"
)

# per-language confusion matrices + per-language P/R/F1
evaluate_per_language(
    y_true=y_true_sbert,
    y_pred=y_pred_sbert,
    langs=test_langs,
    experiment_name="SBERT (multilingual MiniLM)",
    model_name="LogReg"
)

!pip install -q transformers datasets accelerate

from transformers import AutoTokenizer, AutoModelForSequenceClassification, DataCollatorWithPadding
from datasets import Dataset
import torch

mbert_name = "bert-base-multilingual-cased"
tokenizer = AutoTokenizer.from_pretrained(mbert_name)

def make_hf_dataset(texts, labels):
    return Dataset.from_dict({"text": texts, "label": labels})

hf_train = make_hf_dataset(train_texts, train_labels)
hf_val   = make_hf_dataset(val_texts,   val_labels)
hf_test  = make_hf_dataset(test_texts,  test_labels)

def tokenize_batch(batch):
    return tokenizer(
        batch["text"],
        padding=False,
        truncation=True,
        max_length=128  # padding/truncation as on slides
    )

hf_train = hf_train.map(tokenize_batch, batched=True)
hf_val   = hf_val.map(tokenize_batch,   batched=True)
hf_test  = hf_test.map(tokenize_batch,  batched=True)

hf_train.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
hf_val.set_format(  type="torch", columns=["input_ids", "attention_mask", "label"])
hf_test.set_format( type="torch", columns=["input_ids", "attention_mask", "label"])

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

from transformers import TrainingArguments, Trainer

num_labels = 2
model_mbert = AutoModelForSequenceClassification.from_pretrained(
    mbert_name,
    num_labels=num_labels
)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model_mbert.to(device)

MAX_LEN = 128

def encode_texts(texts):
    enc = tokenizer(
        texts,
        padding=True,
        truncation=True,
        max_length=MAX_LEN,
        return_tensors="pt"
    )
    return enc["input_ids"], enc["attention_mask"]

# TRAIN
train_input_ids, train_attention_mask = encode_texts(train_texts)
train_labels_tensor = torch.tensor(train_labels, dtype=torch.long)

# VAL
val_input_ids, val_attention_mask = encode_texts(val_texts)
val_labels_tensor = torch.tensor(val_labels, dtype=torch.long)

# TEST
test_input_ids, test_attention_mask = encode_texts(test_texts)
test_labels_tensor = torch.tensor(test_labels, dtype=torch.long)

train_input_ids.shape, val_input_ids.shape, test_input_ids.shape

import torch
from torch.utils.data import TensorDataset, DataLoader
from torch.optim import AdamW
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, f1_score, recall_score

BATCH_SIZE = 16

train_ds = TensorDataset(train_input_ids, train_attention_mask, train_labels_tensor)
val_ds   = TensorDataset(val_input_ids,   val_attention_mask,   val_labels_tensor)
test_ds  = TensorDataset(test_input_ids,  test_attention_mask,  test_labels_tensor)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE, shuffle=False)

optimizer = AdamW(model_mbert.parameters(), lr=2e-5)
criterion = torch.nn.CrossEntropyLoss()

def eval_loader_mbert(model, loader):
    model.eval()
    all_y, all_p = [], []
    with torch.no_grad():
        for batch in loader:
            input_ids_b, attn_b, labels_b = [t.to(device) for t in batch]
            outputs = model_mbert(
                input_ids=input_ids_b,
                attention_mask=attn_b
            )
            logits = outputs.logits
            preds = logits.argmax(dim=1)

            all_y.append(labels_b.cpu().numpy())
            all_p.append(preds.cpu().numpy())

    all_y = np.concatenate(all_y)
    all_p = np.concatenate(all_p)
    acc = accuracy_score(all_y, all_p)
    return acc, all_y, all_p

EPOCHS = 3

best_val_acc = 0.0
best_state = None

for epoch in range(1, EPOCHS + 1):
    model_mbert.train()
    total_loss = 0.0

    for batch in train_loader:
        input_ids_b, attn_b, labels_b = [t.to(device) for t in batch]

        optimizer.zero_grad()
        outputs = model_mbert(
            input_ids=input_ids_b,
            attention_mask=attn_b,
            labels=labels_b
        )
        loss = outputs.loss
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * input_ids_b.size(0)

    total_loss /= len(train_ds)
    val_acc, _, _ = eval_loader_mbert(model_mbert, val_loader)

    print(f"Epoch {epoch:02d} | train_loss={total_loss:.4f} | val_acc={val_acc:.4f}")

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        best_state = {k: v.cpu().clone() for k, v in model_mbert.state_dict().items()}

# Load best val model
if best_state is not None:
    model_mbert.load_state_dict(best_state)



test_acc_mbert, y_true_mbert, y_pred_mbert = eval_loader_mbert(model_mbert, test_loader)

print("\n=== mBERT finetuned (manual loop) – Overall TEST metrics ===")
print(f"Accuracy: {test_acc_mbert:.4f}")
print(f"F1-score (label=1): {f1_score(y_true_mbert, y_pred_mbert, pos_label=1):.4f}")
print(f"Recall   (label=1): {recall_score(y_true_mbert, y_pred_mbert, pos_label=1):.4f}\n")

print(classification_report(y_true_mbert, y_pred_mbert, digits=4))

# Overall + per-language metrics (accuracy, precision, recall, F1, etc.)
evaluate_per_language(
    y_true=y_true_mbert,
    y_pred=y_pred_mbert,
    langs=test_langs,
    experiment_name="mBERT finetuned (manual loop)",
    model_name="SequenceClassification"
)

# Overall confusion matrix plot
plot_overall_confusion_matrix(
    y_true=y_true_mbert,
    y_pred=y_pred_mbert,
    experiment_name="mBERT finetuned (manual loop)",
    model_name="SequenceClassification"
)

# Per-language confusion matrices
plot_confusion_per_language(
    y_true=y_true_mbert,
    y_pred=y_pred_mbert,
    langs=test_langs,
    experiment_name="mBERT finetuned (manual loop)",
    model_name="SequenceClassification"
)

from sklearn.metrics import accuracy_score, f1_score, recall_score

# --- SBERT metrics (recompute to be safe) ---
acc_sbert = accuracy_score(y_true_sbert, y_pred_sbert)
f1_sbert  = f1_score(y_true_sbert, y_pred_sbert, pos_label=1)
rec_sbert = recall_score(y_true_sbert, y_pred_sbert, pos_label=1)

print("=== SBERT Metrics (TEST) ===")
print("Accuracy:", acc_sbert)
print("F1-score (label=1):", f1_sbert)
print("Recall   (label=1):", rec_sbert)

# --- mBERT metrics (from manual fine-tuning version) ---
# test_acc_mbert, y_true_mbert, y_pred_mbert should come from eval_loader_mbert(...)
acc_mbert = accuracy_score(y_true_mbert, y_pred_mbert)
f1_mbert  = f1_score(y_true_mbert, y_pred_mbert, pos_label=1)
rec_mbert = recall_score(y_true_mbert, y_pred_mbert, pos_label=1)

print("\n=== mBERT Metrics (TEST) ===")
print("Accuracy:", acc_mbert)
print("F1-score (label=1):", f1_mbert)
print("Recall   (label=1):", rec_mbert)

import matplotlib.pyplot as plt
import numpy as np

models = ["SBERT", "mBERT"]
accuracies = [acc_sbert, acc_mbert]

plt.figure(figsize=(5, 4))
plt.bar(models, accuracies)
plt.ylim(0, 1)
plt.ylabel("Accuracy")
plt.title("Accuracy comparison: SBERT vs mBERT")
plt.tight_layout()
plt.show()

metrics_names = ["F1-score", "Recall"]

sbert_values = [f1_sbert,  rec_sbert]
mbert_values = [f1_mbert,  rec_mbert]

x = np.arange(len(metrics_names))
width = 0.35

plt.figure(figsize=(6, 4))
plt.bar(x - width/2, sbert_values, width, label="SBERT")
plt.bar(x + width/2, mbert_values, width, label="mBERT")

plt.xticks(x, metrics_names)
plt.ylim(0, 1)
plt.ylabel("Score")
plt.title("SBERT vs mBERT – F1 & Recall")
plt.legend()
plt.tight_layout()
plt.show()